version: '2'

services:
  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 2181:2181
      - 8181:8181
  zk-smoketest:
    build:
      context: .
      dockerfile: Dockerfile-zk-smoketest
    stdin_open: true
    tty: true
    entrypoint:
      - "/bin/bash"
